language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=unknown-linux-gnu; else OS=apple-darwin; fi
  - export TARGET=$ARCH-$OS
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then PKG=rust-std-$TARGET; else PKG=rustc; fi
  - curl -sO https://static.rust-lang.org/dist/rust-$TRAVIS_RUST_VERSION-$TARGET.tar.gz
  - tar xf rust-$TRAVIS_RUST_VERSION-$TARGET.tar.gz
  - rm -rf $HOME/rust/lib/rustlib/$TARGET
  - mv rust-$TRAVIS_RUST_VERSION-$TARGET/$PKG/lib/rustlib/$TARGET $HOME/rust/lib/rustlib
env:
  matrix:
    - ARCH=x86_64
    - ARCH=i686
notifications:
  email:
    on_success: never
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - g++-multilib

